# Generated by Django 3.2.7 on 2021-09-23 19:38

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='user',
            name='advisor_name',
            field=models.CharField(max_length=25, null=True, verbose_name='نام مشاور'),
        ),
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(null=True, upload_to=account.models.upload_logo, verbose_name='لوگوی بنگاه'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='همراه'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن'),
        ),
    ]
