# Generated by Django 3.2.7 on 2021-11-12 16:18

import account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210923_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(null=True, upload_to=account.models.upload_logo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['PNG', 'JPG', 'JPEG']), account.models.validate_logo_size], verbose_name='لوگوی بنگاه'),
        ),
    ]
