# Generated by Django 3.2.7 on 2021-09-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام بنگاه')),
                ('consultant_name', models.CharField(max_length=20, verbose_name='نام مشاور')),
                ('phone', models.SmallIntegerField(verbose_name='شماره تماس')),
                ('text', models.TextField(verbose_name='آدرس بنگاه و توضیحات بیشتر')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس ها',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.SmallIntegerField(verbose_name='شماره تماس')),
            ],
            options={
                'verbose_name': 'پشتیبانی',
                'verbose_name_plural': 'پشتیبانی',
            },
        ),
    ]
