# Generated by Django 3.2.7 on 2021-11-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_socialnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره تماس'),
        ),
    ]
