# Generated by Django 3.2.7 on 2021-11-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactus_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='شماره تماس'),
        ),
    ]
