# Generated by Django 3.2.7 on 2021-09-05 18:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import estate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('price', models.CharField(max_length=50, verbose_name='قیمت')),
                ('street', models.CharField(max_length=20, verbose_name='خیابان')),
                ('area', models.CharField(max_length=20, verbose_name='متراژ')),
                ('typ', models.CharField(max_length=20, verbose_name='نوع ملک')),
                ('status', models.CharField(choices=[('Rahn', 'رهن'), ('Ejare', 'اجاره'), ('Frosh', 'فروش')], max_length=10, verbose_name='وضعیت')),
                ('room', models.PositiveSmallIntegerField(verbose_name='تعداد اتاق')),
                ('parking', models.PositiveSmallIntegerField(verbose_name='تعداد پارکینگ')),
                ('year_of_construction', models.PositiveSmallIntegerField(verbose_name='سال ساخت')),
                ('address', models.CharField(max_length=50, verbose_name='آدرس')),
                ('img1', models.ImageField(upload_to=estate.models.upload_image, verbose_name='تصویر 1')),
                ('img2', models.ImageField(upload_to=estate.models.upload_image, verbose_name='تصویر 2')),
                ('img3', models.ImageField(upload_to=estate.models.upload_image, verbose_name='تصویر 3')),
                ('img4', models.ImageField(blank=True, null=True, upload_to=estate.models.upload_image, verbose_name='تصویر 4')),
                ('img5', models.ImageField(blank=True, null=True, upload_to=estate.models.upload_image, verbose_name='تصویر 5')),
                ('img6', models.ImageField(blank=True, null=True, upload_to=estate.models.upload_image, verbose_name='تصویر 6')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('is_special_ad', models.BooleanField(default=False, verbose_name='آگهی ویژه')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'ملک',
                'verbose_name_plural': 'املاک',
            },
        ),
    ]
