# Generated by Django 3.2.7 on 2021-09-09 17:57

from django.db import migrations, models
import estate.models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_alter_estate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='slug',
            field=models.SlugField(default=estate.models.generate_slug, editable=False, unique=True, verbose_name='Slug'),
        ),
    ]
