# Generated by Django 3.2.7 on 2021-09-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_alter_estate_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='slug',
        ),
    ]
