# Generated by Django 3.2.7 on 2021-11-12 16:18

import django.core.validators
from django.db import migrations, models
import estate.models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0007_alter_estate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='img1',
            field=models.ImageField(upload_to=estate.models.upload_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['PNG', 'JPG', 'JPEG']), estate.models.validate_img_size], verbose_name='تصویر 1'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='img2',
            field=models.ImageField(upload_to=estate.models.upload_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['PNG', 'JPG', 'JPEG']), estate.models.validate_img_size], verbose_name='تصویر 2'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='img3',
            field=models.ImageField(upload_to=estate.models.upload_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['PNG', 'JPG', 'JPEG']), estate.models.validate_img_size], verbose_name='تصویر 3'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to=estate.models.upload_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['PNG', 'JPG', 'JPEG']), estate.models.validate_img_size], verbose_name='تصویر 4'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to=estate.models.upload_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['PNG', 'JPG', 'JPEG']), estate.models.validate_img_size], verbose_name='تصویر 5'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='img6',
            field=models.ImageField(blank=True, null=True, upload_to=estate.models.upload_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['PNG', 'JPG', 'JPEG']), estate.models.validate_img_size], verbose_name='تصویر 6'),
        ),
    ]
